version: '3.4'
services:
   spigot:
      build: .
      
      container_name: spigot
      restart: always

      environment:
      - EULA=TRUE
      - TYPE=PAPER
      - PAPER_DOWNLOAD_URL=goo.gl/3fuFgC

      volumes:
      - type: bind
        source: /var/world-data
        target: /world-data

      ports:
      - "25565:25565"